-- MySQL Script generated by MySQL Workbench
-- 08/19/17 20:18:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema servicerequest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema servicerequest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `servicerequest` DEFAULT CHARACTER SET utf8 ;
USE `servicerequest` ;

-- -----------------------------------------------------
-- Table `servicerequest`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicerequest`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicerequest`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicerequest`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_type` VARCHAR(45) NOT NULL,
  `room_loc` VARCHAR(45) NOT NULL,
  `room_no` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicerequest`.`check_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicerequest`.`check_in` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `check_in` DATETIME NOT NULL,
  `check_out` DATETIME NOT NULL,
  `room_id` INT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_room1_idx` (`room_id` ASC),
  INDEX `fk_ticket_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_ticket_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `servicerequest`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `servicerequest`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicerequest`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicerequest`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dept_name` VARCHAR(45) NOT NULL,
  `dept_description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicerequest`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicerequest`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_position_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_position_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `servicerequest`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicerequest`.`shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicerequest`.`shift` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sched_start` TIME NOT NULL,
  `sched_end` TIME NOT NULL,
  `department_id` INT NULL,
  `supervisor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shift_department1_idx` (`department_id` ASC),
  INDEX `fk_shift_employee1_idx` (`supervisor` ASC),
  CONSTRAINT `fk_shift_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `servicerequest`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shift_employee1`
    FOREIGN KEY (`supervisor`)
    REFERENCES `servicerequest`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicerequest`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicerequest`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emp_name` VARCHAR(120) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `department_id` INT NULL,
  `position_id` INT NULL,
  `shift_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_department1_idx` (`department_id` ASC),
  INDEX `fk_employee_position1_idx` (`position_id` ASC),
  INDEX `fk_employee_shift1_idx` (`shift_id` ASC),
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `servicerequest`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `servicerequest`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `servicerequest`.`shift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicerequest`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicerequest`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicerequest`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicerequest`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `request_title` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL,
  `time_start` TIMESTAMP NOT NULL,
  `time_end` TIMESTAMP NULL,
  `time_alloted` TIME NULL,
  `escalation_level` INT NULL,
  `desc` TEXT NULL,
  `check_in_id` INT NULL,
  `employee_respond_id` INT NOT NULL,
  `department_id` INT NULL,
  `category_id` INT NULL,
  `employee_create_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_check_in1_idx` (`check_in_id` ASC),
  INDEX `fk_ticket_employee1_idx` (`employee_respond_id` ASC),
  INDEX `fk_ticket_department1_idx` (`department_id` ASC),
  INDEX `fk_ticket_category1_idx` (`category_id` ASC),
  INDEX `fk_ticket_employee2_idx` (`employee_create_id` ASC),
  CONSTRAINT `fk_ticket_check_in1`
    FOREIGN KEY (`check_in_id`)
    REFERENCES `servicerequest`.`check_in` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_employee1`
    FOREIGN KEY (`employee_respond_id`)
    REFERENCES `servicerequest`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `servicerequest`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `servicerequest`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_employee2`
    FOREIGN KEY (`employee_create_id`)
    REFERENCES `servicerequest`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicerequest`.`transcript`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicerequest`.`transcript` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticket_id` INT NOT NULL,
  `ticket_item_id` INT NOT NULL,
  `emp_resp_id` INT NOT NULL,
  `dept_resp_id` INT NOT NULL,
  `description` TEXT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `ticket_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transcript_ticket1_idx` (`ticket_id1` ASC),
  CONSTRAINT `fk_transcript_ticket1`
    FOREIGN KEY (`ticket_id1`)
    REFERENCES `servicerequest`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
